version: "3"

services:

  client:
    image: 071424555001.dkr.ecr.ap-southeast-1.amazonaws.com/tdpk-client:staging
    
    build:
      context: .
      dockerfile: Dockerfile.staging
    ports:
      - 8089:3000
    restart: always