FROM node:alpine

RUN mkdir -p /usr/src/app
ENV PORT 3000

WORKDIR /usr/src/app

COPY . /usr/src/app
RUN rm -f /usr/src/app/.env 
RUN cp /usr/src/app/.env.staging /usr/src/app/.env
RUN yarn install
RUN yarn build

EXPOSE 3000
CMD [ "yarn", "start" ]