export * from './Home';
export * from './Articles';
export * from './ArticleDetails';
export * from './Services';
export * from './ContactUs';
export * from './PrivacyPolicy';
export * from './TermCondition';
export * from './NewsAndPromotions';
export * from './NewsAndPromotionsDetails';
