/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_IfUdzIry2",
    "aws_user_pools_web_client_id": "7hfg1r7f10dcds5j3u68vk1sgp",
    "oauth": {}
};


export default awsmobile;
